site_name: Denver Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Brief: brief.md
  - Modules:
      - bcli: modules/bcli.md
      - bdtp: modules/bdtp.md
      - bdtpfserv: modules/bdtpfserv.md
      - bitmap: modules/bitmap.md
      - crypt: modules/crypt.md
      - ctext: modules/ctext.md
      - datau: modules/datau.md
      - datp: modules/datp.md
      - get: modules/get.md
      - graphics3d: modules/graphics3d.md
      - handypy: modules/handypy.md
      - log: modules/log.md
      - pysetup: modules/pysetup.md
      - rawd: modules/rawd.md
      - sound: modules/sound.md
      - text: modules/text.md
theme:
  name: material